packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^22.0.0
  typescript: ^5.8.0
  tsup: ^8.0.0
  prettier: ^3.0.0
  vite: ^7.3.1
  axios: ^1.7.0
  mitt: ^3.0.0
  ramda: ^0.30.0
  '@types/ramda': ^0.30.0
  '@types/lodash': ^4.17.0
  date-fns: ^4.1.0
  lodash: ^4.17.21
  uuid: ^11.0.0
  '@types/uuid': ^10.0.0
  winston: ^3.19.0
