export { recorderManager, initManager, addRecorderWithAutoIncrementId, enableRecordEvents, getSavePath, saveDB } from './core/manager-init'
export type { RecorderExtra, ManagerConfig } from './core/manager-init'
export { paths } from '@autorecord/core'
export { logger, setJsonMode, isJsonMode, outputJson, outputTable, outputSuccess, outputError } from './core/output'
export { initDB, getRecorders, getRecords, insertRecord, updateRecordStopData } from './core/db'
export type { DatabaseSchema, RecordModel, RecorderModel, QueryRecordsOpts } from './core/db'
export { isServerRunning } from './core/server-detect'

export { createResolveCommand } from './commands/resolve'
export { createListCommand } from './commands/list'
export { createAddCommand } from './commands/add'
export { createRemoveCommand } from './commands/remove'
export { createStatusCommand } from './commands/status'
export { createStartCommand } from './commands/start'
export { createStopCommand } from './commands/stop'
export { createCheckCommand } from './commands/check'
export { createWatchCommand } from './commands/watch'
export { createConfigCommand } from './commands/config'
export { createRecordsCommand } from './commands/records'
